# -*- coding: utf-8 -*-
"""task 14  (ETL).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZBLwPzqP9Vgqgzobtw5Kao1gzgvnVaw
"""

import pandas as pd


df = pd.read_csv("credit_card.csv")


df.shape

#step1:
df.head(10)

# step 2: checking null value
df.isnull().sum()

df.columns = (
     df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)


df.columns

df['week_start_date'] = pd.to_datetime(df['week_start_date'])

df['use_chip'] = df['use_chip'].str.strip()


df['delinquent_acc'] = df['delinquent_acc'].astype(int)

df.info()

# Credit utilization percentage

df['credit_utilization_pct'] = (
    df['total_revolving_bal'] / df['credit_limit']
) * 100

df['credit_utilization_pct']

# Average transaction value

df['avg_transaction_value'] = (
    df['total_trans_amt'] / df['total_trans_vol']
)

df['avg_transaction_value']