# -*- coding: utf-8 -*-
"""Task 5 ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TcXuHV3foy1knWJAJrPMcGQWw-91Ca35
"""

import pandas as pd

df = pd.read_csv('Car_sales.csv')

df.head()

df.info()

df.isnull().sum()

empty_col =['__year_resale_value','Price_in_thousands','Engine_size','Horsepower','Wheelbase','Width','Length','Curb_weight','Fuel_capacity','Fuel_efficiency','Power_perf_factor']

for col in empty_col:
 df[col]=df[col].fillna(df[col].mean())

df.info()
print(" ")
df.isnull().sum()

df.shape
print(" ")

df = df.drop_duplicates()
print(" ")

df.shape

df['Latest_Launch'].head(10)

df['Latest_Launch'] = df['Latest_Launch'].astype(str).str.strip()

df['Latest_Launch'] = df['Latest_Launch'].replace(
    ['nan', 'NaN', ' ', '', 'NA', 'N/A', 'None'],
    pd.NA)