# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpHB7797r-XH-IGGlAO0mthu_o6R6qCm
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np


patient = pd.read_csv(r"patient file.csv")
patient

# Display first few rows
patient.head(6)

# Data info (datatypes, missing values)

patient.info()

# summary of numeric values.

patient.describe()

# value counts for Age column

patient['Age'].value_counts()

# Histogram for Age , BP and Chlstrl data

fig,axis = plt.subplots(1,3,figsize = (15,5))

# Age
sns.histplot(patient['Age'], bins=8, kde = True, color='skyblue', edgecolor = 'black', ax= axis[0])
axis[0].set_title("Age Distribution", fontsize = 16, weight = 'bold')
axis[0].set_xlabel("Age")
axis[0].set_ylabel("Frequency")

# BP
sns.histplot(patient['BP'], bins = 8, kde = True, color ='lightgreen', edgecolor ='black', ax= axis[1])
axis[1].set_title("Blood Pressure", fontsize = 16, weight = 'bold')
axis[1].set_xlabel("Blood Pressure")
axis[1].set_ylabel("Frequency")

# Cholesterol
sns.histplot(patient['Chlstrl'], bins = 8, kde = True, color = 'brown', edgecolor = 'black', ax = axis[2])
axis[2].set_title("Cholesterol", fontsize = 16, weight = 'bold')
axis[2].set_xlabel("Cholesterol")
axis[2].set_ylabel("Frequency")

# Scatter Plot

# Scatter plot: Age vs DrugR1
plt.scatter(patient['Age'],patient['DrugR1'], color = 'purple')
plt.title("Age vs DrugR1")
plt.xlabel("Age")
plt.ylabel("DrugR1")
plt.show()

# Scatter plot: BP vs DrugR1
plt.scatter(patient['BP'], patient['DrugR1'], color='orange')
plt.title('BP vs DrugR1')
plt.xlabel('BP')
plt.ylabel('DrugR1')
plt.show()


# Scatter plot: Chlstrl vs DrugR1
plt.scatter(patient['Chlstrl'], patient['DrugR1'], color='teal')
plt.title('Chlstrl vs DrugR1')
plt.xlabel('Chlstrl')
plt.ylabel('DrugR1')
plt.show()

# Box Plot for Age

plt.figure(figsize = (9,6))
sns.boxplot(x = patient['Age'], color = 'skyblue')
plt.title("Box Plot for Age")
plt.xlabel("Age")
plt.show()

# correlation heatmap

plt.figure(figsize=(10,6))
sns.heatmap(patient.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# pairplot (see trends and clusters)

sns.pairplot(patient, hue="Age")
plt.show()

