# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jnc407CmD4niID2RGHjow0FREjrJP1c
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel("Vrinda Store Analysis.xlsx")
df.info()

df.head()

pivot = df.pivot_table(
    index="Month",
    values=["Order ID", "Amount"],
    aggfunc={"Order ID": "count", "Amount": "sum"}
)

pivot.plot(
    kind="bar",
    secondary_y="Amount",
    figsize=(10,5)
)

plt.title("Monthly Orders vs Revenue")
plt.show()

# orders : channel
channel_count = df['Channel '].value_counts()
print(channel_count)

plt.figure(figsize=(6,6))
plt.pie(channel_count,labels=channel_count.index,autopct='%1.1f%%')
plt.title("Order Distribution by Channel")
plt.show()

# order status
channel_status = df['Status'].value_counts()
print(channel_status)

plt.figure(figsize=(6,6))
plt.pie(channel_status,labels=channel_status.index,autopct='%1.1f%%')
plt.title("Order status")
plt.show()

# men vs women
gender_amount = df.groupby("Gender")["Amount"].sum()
plt.figure(figsize=(6,6))
plt.pie(gender_amount,labels=gender_amount.index,autopct='%1.1f%%')

plt.title("Shopping Amount Distribution by Gender")
plt.show()

# top 10 state
top_states = (df.groupby('ship-state')["Amount"].sum().head(10).sort_values(ascending=False))
print(top_states)
print("  ")

plt.figure(figsize=(10,5))
top_states.plot(kind="bar")
plt.title("Top 10 States by Total Sales Amount")
plt.xlabel("State")
plt.ylabel("Total Amount")
plt.xticks(rotation=45)
plt.grid(axis="y")
plt.show()